# Imports and pip installations (if needed)

In [1]:
from sklearn.datasets import load_iris

import pandas as pd
import numpy as np

# Part 1: Load the dataset

In [2]:
# Load the dataset (load remotely, not locally)

# load the data
iris = load_iris()

# Display to console
print( "Data: ") 
print( iris.data[:10])
print( "\nFeature Names:", end = "  " )
print( iris.feature_names )
print( "\nTarget: ", end = " ")
print(iris.target)
print("\nTarget Names: ", end = " ")
print(iris.target_names)

Data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Feature Names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

Target Names:  ['setosa' 'versicolor' 'virginica']


In [3]:
# Put everything nicely in a single DataFrame
featureDataFrame = pd.DataFrame( data = iris.data, columns = iris.feature_names, )
listTarget_names = [f'{iris.target_names[0]}']*50 + [f'{iris.target_names[1]}']*50 + [f'{iris.target_names[2]}']*50
speciesDataFrame = pd.DataFrame( data = listTarget_names, columns = ['species'])
targetDataFrame = pd.DataFrame( data = iris.target, columns = ['target'] )
irisDataFrame = pd.concat( [featureDataFrame, speciesDataFrame,targetDataFrame ], axis = 1)

# Output the first 15 rows of the data
irisDataFrame.head(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   

   species  target  
0   setosa       0  
1   setosa       0  
2   setosa       0  
3   setosa       0  
4   setosa       0  
5   setosa       0  
6   setosa       0  
7   setosa       0  
8   setosa       0  
9   setosa       0  
10  setosa       0  
11  setosa       0  
12  setosa       0  
13  setosa       0  
14  setosa       0

In [6]:
# Display a summary of the table information (number of datapoints, etc.)
irisDataFrame.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object 
 5   target             150 non-null    int32  
dtypes: float64(4), int32(1), object(1)
memory usage: 6.6+ KB


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

![picture](https://raw.githubusercontent.com/billydavila/CSC448/main/Judging%20Flowers/irisPic.png)




![pic](https://raw.githubusercontent.com/billydavila/CSC448/main/Judging%20Flowers/iris-datasetPic.png)